apiVersion: v1
kind: ServiceAccount
metadata:
    name: ovnkube-cluster-manager
    namespace: ovn-kubernetes

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: ovnkube-cluster-manager
roleRef:
    name: ovnkube-cluster-manager
    kind: ClusterRole
    apiGroup: rbac.authorization.k8s.io
subjects:
    - kind: ServiceAccount
      name: ovnkube-cluster-manager
      namespace: ovn-kubernetes

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: ovnkube-cluster-manager-configmaps
    namespace: ovn-kubernetes
roleRef:
    name: ovn-k8s-configmap
    kind: Role
    apiGroup: rbac.authorization.k8s.io
subjects:
    - kind: ServiceAccount
      name: ovnkube-cluster-manager
      namespace: ovn-kubernetes

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: ovnkube-cluster-manager
rules:
    - apiGroups: [""]
      resources:
          - namespaces
          - nodes
          - pods
          - services
          - endpoints
      verbs: [ "get", "list", "watch" ]
    - apiGroups: ["discovery.k8s.io"]
      resources:
          - endpointslices
      verbs: [ "get", "list", "watch" ]
    - apiGroups: ["k8s.cni.cncf.io"]
      resources:
          - ipamclaims
          - network-attachment-definitions
          - multi-networkpolicies
      verbs: ["list", "get", "watch"]
    - apiGroups: [ "k8s.cni.cncf.io" ]
      resources:
      - ipamclaims/status
      - network-attachment-definitions
      verbs: [ "patch", "update" ]
    - apiGroups: [ "k8s.cni.cncf.io" ]
      resources:
      - network-attachment-definitions
      verbs: [ "create", "delete" ]
    - apiGroups: ["k8s.ovn.org"]
      resources:
          - egressips
          - egressservices
          - adminpolicybasedexternalroutes
          - egressfirewalls
          - egressqoses
          - networkqoses
          - userdefinednetworks
      verbs: [ "get", "list", "watch" ]
    - apiGroups: ["k8s.ovn.org"]
      resources:
          - egressips
          - egressservices/status
          - networkqoses/status
          - userdefinednetworks
          - userdefinednetworks/status
      verbs: [ "patch", "update" ]
    - apiGroups: [""]
      resources:
          - events
      verbs: ["create", "patch", "update"]
    - apiGroups: [""]
      resources:
          - pods/status # used in multi-homing: https://github.com/ovn-org/ovn-kubernetes/blob/a9beb6fd4f8ea32b264999a8ebec25cd6bdc2281/go-controller/pkg/util/pod.go#L49
          - nodes/status
          - services/status
      verbs: [ "patch", "update" ]
    - apiGroups: ["k8s.ovn.org"]
      resources:
        - adminpolicybasedexternalroutes/status
        - egressfirewalls/status
        - egressqoses/status
      verbs: [ "patch", "update" ]
    - apiGroups: ["policy.networking.k8s.io"]
      resources:
          - adminnetworkpolicies
          - baselineadminnetworkpolicies
      verbs: [ "list" ]
    - apiGroups: ["policy.networking.k8s.io"]
      resources:
          - adminnetworkpolicies/status
          - baselineadminnetworkpolicies/status
      verbs: [ "patch" ]

    {{- if eq (hasKey .Values.global "enableNetworkSegmentation" | ternary .Values.global.enableNetworkSegmentation false) true }}
    - apiGroups: ["discovery.k8s.io"]
      resources:
          - endpointslices
      verbs: [ "create", "update", "delete", "deletecollection" ]
    {{- end }}
    {{- if eq (hasKey .Values.global "enableDNSNameResolver" | ternary .Values.global.enableDNSNameResolver false) true }}
    - apiGroups: ["network.openshift.io"]
      resources:
          - dnsnameresolvers
      verbs: [ "create", "delete", "list", "patch", "update", "watch" ]
    {{- end }}
