sudo: required
language: go
go:
      - 1.11.4
before_install:
    - export GOPATH=$HOME/go
    - export PATH=$HOME/usr/local/go/bin:$GOPATH/bin:$PATH
    - mkdir -p $GOPATH/src/github.com/ovn-org
    - mv $TRAVIS_BUILD_DIR $GOPATH/src/github.com/ovn-org/ovn-kubernetes
    - cd $GOPATH/src/github.com/ovn-org/ovn-kubernetes
install:
    - eval "$(gimme 1.11.4)"
script:
    - pushd go-controller
    -    make
    -    make windows
    -    make gofmt
    -    make install.tools
    -    make lint
    -    make check
    - popd
    - pushd dist/images
    -    if [ -n "$(git diff --stat origin/master.. | grep dist/images/Dockerfile)" ]; then make all; fi
    - popd
