sudo: required
language: go
go:
      - 1.10.4
before_install:
    - export GOPATH=$HOME/go
    - export PATH=$HOME/usr/local/go/bin:$GOPATH/bin:$PATH
    - mkdir -p $GOPATH/src/github.com/ovn-org
    - mv $TRAVIS_BUILD_DIR $GOPATH/src/github.com/ovn-org/ovn-kubernetes
    - cd $GOPATH/src/github.com/ovn-org/ovn-kubernetes
install:
    - eval "$(gimme 1.10.4)"
script:
    -   cd go-controller;
    -    make;
    -    make windows;
    -    make gofmt;
    -    make install.tools;
    -    make lint;
    -    make check;
