site_name: OVN Kubernetes
site_url: https://www.ovn.org/ovn-kubernetes/
repo_url: https://github.com/ovn-org/ovn-kubernetes
repo_name: ovn-org/ovn-kubernetes
edit_uri: edit/master/docs
extra_css:
  - stylesheets/extra.css
site_dir: site
docs_dir: docs
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  logo: images/ovn-inside-k8s.png
  favicon: images/ovn-inside-k8s.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate
    - navigation.instant.preview
plugins:
  - search
  - awesome-pages
  - mike
  - macros:
      #include_dir: examples
      j2_line_comment_prefix: "#$"
  - blog:
      # NOTE: configuration options can be found at
      # https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/
      blog_dir: blog
      blog_toc: true
      post_excerpt: required
      post_excerpt_max_authors: 2
markdown_extensions:
  - admonition
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: site-src
      check_paths: true
  - toc:
      permalink: true
nav:
  - Introduction: index.md
  - Overview:
    - Architecture: design/architecture.md
    - Network Topology: design/topology.md
    - Gateway Modes: design/gateway-modes.md
    - Traffic Flows: design/traffic-flows.md
    - Pod Creation Workflow: design/pod-creation-workflow.md
    - Service Creation Workflow: design/service-creation-workflow.md
    - Service Traffic Policy: design/service-traffic-policy.md
    - Host To NodePort Hairpin: design/host-to-node-port-hairpin-trafficflow.md
    - ExternalIPs/LoadBalancerIngress: design/external-ip-and-loadbalancer-ingress.md
    - Internal Subnets: design/ovn-kubernetes-subnets.md
    - Kubevirt VM Live Migration: design/live-migration.md
  - Getting Started:
    - OVN Kubernetes Overview: getting-started/overview.md
    - Launching OVN Kubernetes: getting-started/launching-ovn-kubernetes.md
    - Deploying Workloads on OVN Kubernetes cluster: getting-started/example-pod-creation.md
    - Deploying Services on OVN Kubernetes cluster: getting-started/example-service-creation.md
    - Setup and Building: getting-started/building-ovn-kubernetes.md
    - Run OVN Kubernetes From Release Image: getting-started/running-release.md
    - Run OVN Kubernetes From RPM: getting-started/running-rpm.md
    - CLI Guide: getting-started/cli-guide.md
    - Configuration Guide: developer-guide/configuration.md
  - Developer Guide:
      - Contributing Guide: governance/CONTRIBUTING.md
      - Reviewing Guide: governance/REVIEWING.md
      - Coding Guide: developer-guide/developer.md
      - Kubernetes CRD API-Reference Guide:
        - EgressIP: developer-guide/egress-ip-api-spec.md
        - EgressService: developer-guide/egress-service-api-spec.md
        - EgressQoS: developer-guide/egress-qos-api-spec.md
        - EgressFirewall: developer-guide/egress-firewall-api-spec.md
        - AdminPolicyBasedExternalRoutes: developer-guide/admin-epbr-api-spec.md
      - OVN Kubernetes Container Images: developer-guide/image-build.md
      - Documentation Guide: developer-guide/documentation.md
      - Local Testing Guide: developer-guide/testing.md
      - CI Testing Guide: ci/ci.md
      - Web Design Guide: developer-guide/web-design.md
      - Debugging: developer-guide/debugging.md
      - Releasing: developer-guide/release.md
  - Features:
    - ClusterEgressControls:
      - EgressIP: features/cluster-egress-controls/egress-ip.md
      - EgressService: features/cluster-egress-controls/egress-service.md
      - EgressQoS: features/cluster-egress-controls/egress-qos.md
      - EgressGateway: features/cluster-egress-controls/egress-gateway.md
    - NetworkSecurityControls:
      - NetworkPolicy: features/network-security-controls/network-policy.md
      - AdminNetworkPolicy: features/network-security-controls/admin-network-policy.md
      - EgressFirewall: features/network-security-controls/egress-firewall.md
    - InfrastructureSecurityControls:
      - NodeIdentity: features/infrastructure-security-controls/node-identity.md
    - MultiNetworking:
      - Multihoming: features/multi-homing.md
    - Multicast: features/multicast.md
    - LiveMigration: features/live-migration.md
    - HybridOverlay: features/hybrid-overlay.md
    - Hardware Offload:
      - OVS Offload: features/hardware-offload/ovs_offload.md
      - Support DPU Acceleration: features/hardware-offload/dpu-acceleration.md
  - Troubleshooting:
    - Introduction: troubleshooting/debugging.md
    - OVNKube Trace: troubleshooting/ovnkube-trace.md
    - Logging: troubleshooting/logging.md
  - Observability:
    - Metrics: observability/metrics.md
  - Blog:
    - blog/index.md
