---
- name: Kubernetes | include global vars for minions
  include_vars: "{{ansible_tmp_dir}}/generated_global_vars.yml"
  when: not master

- name: Kubernetes | include vars
  include_vars: "{{ ansible_os_family|lower }}.yml"

- name: Kubernetes | fetch network details
  include_tasks: set_ip_facts.yml

# We need to start kubelet in order to be able to retrieve the ovn_host_subnet from kubernetes
# node annotations
- name: Kubernetes | Register and start kubelet service
  include_tasks: ./start_kubelet.yml

- name: Kubernetes | Fetch OVN subnet for the node
  include_tasks: ./get_ovn_subnet.yml

# This will create the HNS network if it doesn't exist, or get its HNS id if
# it was already previously created.
- name: Kubernetes | Setup SDN
  include_tasks: ./setup_sdn.yml

- name: Kubernetes | Check powershell execution policy
  win_shell: Get-ExecutionPolicy
  register: execution_policy
  changed_when: false

- name: Kubernetes | Set execution_policy_required variable
  set_fact:
    execution_policy_required: "{{ true if execution_policy.stdout_lines[0] == 'Restricted' else false}}"

- name: Kubernetes | Enable unrestricted execution policy for powershell scripts
  win_shell: Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force
  changed_when: false
  when: execution_policy_required

- name: Kubernetes | OVS Docker network setup
  include_tasks: ./setup_ovs_docker.yml

- name: Kubernetes | refresh network details
  include_tasks: set_ip_facts.yml

- name: Kubernetes | Check ping to OVN gateway
  win_shell: ping {{OVN_GATEWAY_IP}} -n 1
  register: ping_ovn_gateway
  ignore_errors: true
  changed_when: false

- name: Kubernetes | Check if minion-init has executed already
  block:
    - debug:
        msg: Could not reach OVN gateway, running minion init
    # This will create another powershell script for minion init. OVS on Windows
    # does not allow any commands to be ran through network. Ansible uses WinRM
    # for the connection.
    - name: Kubernetes | Run minion-init
      include_tasks: ./run_minion_init.yml
  when: ping_ovn_gateway.rc != 0

- name: Kubernetes | Change to restricted execution policy for powershell scripts
  win_shell: Set-ExecutionPolicy -ExecutionPolicy Restricted -Force
  changed_when: false
  when: execution_policy_required

# There is no infra container for Windows Server, this creates a custom
# infra container
- name: Kubernetes | Check if infra container exists
  win_shell: "docker image inspect {{kubernetes_info.infracontainername}}"
  register: infra_inspect
  failed_when: infra_inspect.rc != 0 and infra_inspect.rc != 1
  changed_when: false
  when: ansible_kernel in supported_versions_by_the_playbook

- include_tasks: ./create_infracontainer.yml
  when: infra_inspect.rc != 0 and ansible_kernel in supported_versions_by_the_playbook

- name: Create test yaml for this host
  become: true
  become_method: sudo
  blockinfile:
    path: /root/nano-pod-{{windows_container_tag}}-{{ansible_hostname|lower}}.yaml
    create: yes
    marker: "# {mark} Ansible automatic example generation"
    block: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: nano-{{windows_container_tag}}-{{ansible_hostname|lower}}
        labels:
          name: webserver
      spec:
        containers:
        - name: nano
          image: ovnkubernetes/pause
          imagePullPolicy: IfNotPresent
        # This test yaml uses a custom nanoserver container that starts a simple
        # http server that can be used for tests. It's much faster compared to the
        # IIS container.
        - name: nano2
          image: alinbalutoiu/nanoserver-web:{{windows_container_tag}}
          imagePullPolicy: IfNotPresent
        nodeSelector:
          beta.kubernetes.io/os: windows
          kubernetes.io/hostname: {{ansible_hostname|lower}}
  delegate_to: "{{ item }}"
  with_items: "{{groups['kube-master']}}"
