apiVersion: v1
kind: ServiceAccount
metadata:
    name: ovnkube-db
    namespace: ovn-kubernetes

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: ovnkube-db
roleRef:
    name: ovnkube-db
    kind: ClusterRole
    apiGroup: rbac.authorization.k8s.io
subjects:
    - kind: ServiceAccount
      name: ovnkube-db
      namespace: ovn-kubernetes

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: ovnkube-db-ep
    namespace: ovn-kubernetes
roleRef:
    name: ovnkube-db-ep
    kind: Role
    apiGroup: rbac.authorization.k8s.io
subjects:
    - kind: ServiceAccount
      name: ovnkube-db
      namespace: ovn-kubernetes

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: ovnkube-db
rules:
    - apiGroups: [""]
      resources:
          - nodes
          - namespaces
      verbs: [ "get", "list", "watch" ]

# ovnkube-db startup scripts create an endpoint:
# https://github.com/ovn-org/ovn-kubernetes/blob/d3b10e87f7fffa38fdf4ad52f98bc8ba998df6c2/dist/images/ovnkube.sh#L699
# in HA statefulsets/pods are inspected 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: ovnkube-db-ep
    namespace: ovn-kubernetes
rules:
    - apiGroups: [""]
      resources:
          - endpoints
      verbs: [ "get", "create" ]
    - apiGroups: [""]
      resources:
          - pods
      verbs: [ "get", "list" ]
    - apiGroups: ["apps"]
      resources:
          - statefulsets
      verbs: [ "get" ]
