nbLogLevel: "-vconsole:info -vfile:info"
sbLogLevel: "-vconsole:info -vfile:info"
northdLogLevel: "-vconsole:info -vfile:info"
ovnkubeNodeLogLevel: 4
ovnControllerLogLevel: "-vconsole:info"
logFileMaxSize: 100
logFileMaxBackups: 5
logFileMaxAge: 5
libovsdbClientLogFile: ""