name: commands
on:
  issue_comment:
    types: [created]

concurrency: commands-${{ github.ref }}

jobs:
  retest:
    if: |
      github.event.issue.pull_request && 
      (
        contains(github.event.comment.body, '/retest') || 
        contains(github.event.comment.body, '/retest-failed') || 
        contains(github.event.comment.body, '/cancel') || 
        contains(github.event.comment.body, '/help')
      ) 
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Re-Test Action
        uses: ./.github/actions/retest-action
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
